# token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MmJiYTY2NmQ3ZDE3Mjg1MzUxYzU2MyIsImlhdCI6MTcxNDE2MDY2MH0.iqVedrNysTUThJ7XEcd-DBldbYSbTDi1UNeB7xQSr6Q
POST http://localhost:3000/signin
Content-Type: application/json

{
    "fullname": "Lê Tân",
    "email": "201146@dlu.edu.vn",
    "password": "LeTan12345",
    "clas": "CTK44A",
    "faculty": "CNTT",
    "dateOfBirth": "2002/02/20",
    "role": "Sinh viên"
}

# POST http://localhost:3000/change-password
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MDE4OTljNGQ4NzY3OTVjZjIyMjBjNSIsImlhdCI6MTcxMjEyMzQ1OH0.e_55a2DL_HhCpjcSX5KmdhkbGBev2tpZSuBEAwQGieU

# {
#     "currentPassword": "Letan12345",
#     "newPassword": "LeTan12345"
# }

# GET http://localhost:3000/get-upload-url

# POST http://localhost:3000/create-blog
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MDE4OTljNGQ4NzY3OTVjZjIyMjBjNSIsImlhdCI6MTcxMjEyMzQ1OH0.e_55a2DL_HhCpjcSX5KmdhkbGBev2tpZSuBEAwQGieU

# {
#     "title": "blog test #2sdf",
#     "banner": "https://example.com/image.jpg",
#     "des": "des test",
#     "content": {
#         "blocks": [ 1, 2 ]
#     },
#     "tags": [ "1", "2" ]
# }

# GET  http://localhost:3000/latest-blogs

# GET  http://localhost:3000/trending-blogs

# POST  http://localhost:3000/search-blogs
# Content-Type: application/json

# {
#     "tag": "tag 1"
# }

# POST  http://localhost:3000/search-users
# Content-Type: application/json

# {
#     "query": "letan"
# }

# POST  http://localhost:3000/get-profile
# Content-Type: application/json

# {
#     "username": "letanphoto202"
# }

# POST  http://localhost:3000/get-blog
# Content-Type: application/json

# {
#     "blog_id": "React-la-gi-D5ivQKbzog23szrj5VIKh"
# }


# POST http://localhost:3000/create-event
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MDE4OTljNGQ4NzY3OTVjZjIyMjBjNSIsImlhdCI6MTcxMjEyMzQ1OH0.e_55a2DL_HhCpjcSX5KmdhkbGBev2tpZSuBEAwQGieU

# {
#     "title": "blog test #2sdf",
#     "banner": "https://example.com/image.jpg",
#     "des": "des test",
#     "content": {
#         "blocks": [ 1, 2 ]
#     }
# }

# GET  http://localhost:3000/new-notification
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MmJiYTY2NmQ3ZDE3Mjg1MzUxYzU2MyIsImlhdCI6MTcxNDE2MDY2MH0.iqVedrNysTUThJ7XEcd-DBldbYSbTDi1UNeB7xQSr6Q